
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xf6\xbd\xb2\xfdF\x80\x81w_\xcb\xd8\xc4G^\x86\x8b'
    
_lr_action_items = {'TEXT_FILE':([5,],[6,]),'RPAREN':([13,],[14,]),'USER_DEFINE':([5,],[7,]),'VAL':([0,1,3,8,9,10,12,14,],[-2,2,-1,-3,-4,-5,-6,-7,]),'NUMBER':([5,],[8,]),'EQUALS':([4,],[5,]),'LPAREN':([6,],[11,]),'STRING':([7,11,],[12,13,]),'ID':([2,],[4,]),'$end':([0,1,3,8,9,10,12,14,],[-2,0,-1,-3,-4,-5,-6,-7,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'VAL_DECL_INIT':([0,],[1,]),'USER_DEFINE_VALUE':([5,],[9,]),'VAL_DECL':([1,],[3,]),'RDD_INIT':([5,],[10,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> VAL_DECL_INIT","S'",1,None,None,None),
  ('VAL_DECL_INIT -> VAL_DECL_INIT VAL_DECL','VAL_DECL_INIT',2,'p_val_declare_init','test.py',96),
  ('VAL_DECL_INIT -> <empty>','VAL_DECL_INIT',0,'p_val_declare_init','test.py',97),
  ('VAL_DECL -> VAL ID EQUALS NUMBER','VAL_DECL',4,'p_val_declare','test.py',101),
  ('VAL_DECL -> VAL ID EQUALS USER_DEFINE_VALUE','VAL_DECL',4,'p_val_declare','test.py',102),
  ('VAL_DECL -> VAL ID EQUALS RDD_INIT','VAL_DECL',4,'p_val_declare','test.py',103),
  ('USER_DEFINE_VALUE -> USER_DEFINE STRING','USER_DEFINE_VALUE',2,'p_user_define_value','test.py',110),
  ('RDD_INIT -> TEXT_FILE LPAREN STRING RPAREN','RDD_INIT',4,'p_rdd_init','test.py',116),
]
